#!/bin/bash
# Adam Cockell
# looks for jira items labeled with project_managed_connect

username=$1
password=$2
stakeholder_email=$3 #comma seperated
sender_email=$4

echo "If you are receiving this email, you are either a project stakeholder or blocker to the release process.  The following items require your immediate attention.  Please update and/or complete these tickets as soon as possible to move the project forward." > manage_report
echo "" >> manage_report

function process {
changes=$1
other_count=$(cat manage_response | jsawk -n 'out(this.issues)' | jsawk -a 'return this.length')
emails=""

for (( cnt=0; cnt<$other_count; cnt++ ))
do   
  interested_in=$(cat manage_response | jsawk -n "out(this.issues[$cnt])")
  issue_assignee=$(echo $interested_in | jsawk -n "out(this.fields.assignee.displayName)")
  issue_email=$(echo $interested_in | jsawk -n "out(this.fields.assignee.emailAddress)")
  issue_assignee_username=$(echo $interested_in | jsawk -n "out(this.fields.assignee.name)")
  issue_summary=$(echo $interested_in | jsawk -n "out(this.fields.summary)")
  issue_key=$(echo $interested_in | jsawk -n "out(this.key)")
  issue_status=$(echo $interested_in | jsawk -n "out(this.fields.status.name)")
  issue_status_id=$(echo $interested_in | jsawk -n "out(this.fields.status.id)")
  issue_estimate=$(echo $interested_in | jsawk -n "out(this.fields.aggregatetimeoriginalestimate)")
  issue_description=$(echo $interested_in | jsawk -n "out(this.fields.description)")

  if [ $changes -eq 0 ]; then
    emails="$issue_email,$emails"
    echo "" >> manage_report
    echo "$issue_assignee : $issue_summary  ( $issue_status )" >> manage_report
    echo "Description: $issue_description" >> manage_report
    echo "Link: https://radiumone.jira.com/browse/$issue_key" >> manage_report
    echo "---------------------------------------------------------------------------------" >> manage_report
  else
    echo "$issue_assignee : https://radiumone.jira.com/browse/$issue_key" >> manage_report
  fi
done

}

curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$password "https://radiumone.jira.com/rest/api/2/search?jql=labels="project_managed_connect"%20AND%20status!="Closed"%20AND%20status!="Done"%20AND%20status!="Resolved"%20AND%20updated%3E=-1d%20AND%20issuetype!="Epic"+order+by+assignee&maxResults=1000" > manage_response
echo "Updated in the last 24 hours:" >> manage_report
process 1

curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$password "https://radiumone.jira.com/rest/api/2/search?jql=labels="project_managed_connect"%20AND%20status!="Closed"%20AND%20status!="Done"%20AND%20stat     us!="Resolved"%20AND%20issuetype!="Epic"+order+by+assignee&maxResults=1000" > manage_response
echo "" >> manage_report
echo "Outstanding blockers:" >> manage_report
process 0

echo "" >> manage_report
echo "If you have an unlisted blocker, please reply to this email." >> manage_report
echo "" >> manage_report
echo "Thank you" >> manage_report
echo "$sender_email" >> manage_report

echo $emails
emails="" # for debugging
mail -s "Connect Project Blocker Status" -F "$stakeholder_email,$emails" -f "$sender_email" < manage_report
