#!/bin/bash
# Adam Cockell
# 7/9/14

# Scenario 1
# Get count of all completed issues per sprint and arrange by assignee
# Include total original time estimate per iteration
# Do this for every sprint so we have a running history of output per assignee

# Scenario 2
# Get current progress on each epic
# Print out complete and incomplete issues for each
# Email to stakeholders

username=$1
pass=$2
sprints=(126 125) #sprints in descending order
sprint_count=${#sprints[@]}

rm -rf dev_remaining
rm -rf dev_report

echo "---------------"
echo "Finding Epics: "
curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$pass "https://radiumone.jira.com/rest/api/2/search?jql=project="Datatech"%20AND%20issuetype="Epic"%20AND%20labels=DWPM&maxResults=1000" > epic_response
epic_count=$(cat epic_response | jsawk -n 'out(this.issues)' | jsawk -a 'return this.length')
echo $epic_count epics


epic_summary=()
epic_key=()
for (( cnt=0; cnt<$epic_count; cnt++ ))
do
  interested_in=$(cat epic_response | jsawk -n "out(this.issues[$cnt])")
  epic_key[cnt]=$(echo $interested_in | jsawk -n "out(this.key)")
  epic_summary[cnt]=$(echo $interested_in | jsawk -n "out(this.fields.summary)")
  echo "${epic_key[cnt]} | ${epic_summary[cnt]}" >> epics
done

for sprint in "${sprints[@]}"
do

  curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$pass "https://radiumone.jira.com/rest/api/2/search?jql=project="Datatech"%20AND%20issuetype!="Epic"%20AND%20labels=DWPM%20AND%20sprint=$sprint+order+by+assignee&maxResults=1000" > sprint_response
  other_count=$(cat sprint_response | jsawk -n 'out(this.issues)' | jsawk -a 'return this.length')

  for (( cnt=0; cnt<$other_count; cnt++ ))
  do
    interested_in=$(cat sprint_response | jsawk -n "out(this.issues[$cnt])")
    issue_assignee=$(echo $interested_in | jsawk -n "out(this.fields.assignee.displayName)")
    issue_assignee_username=$(echo $interested_in | jsawk -n "out(this.fields.assignee.name)")
    issue_summary=$(echo $interested_in | jsawk -n "out(this.fields.summary)")
    issue_key=$(echo $interested_in | jsawk -n "out(this.key)")
    issue_status=$(echo $interested_in | jsawk -n "out(this.fields.status.name)")
    issue_status_id=$(echo $interested_in | jsawk -n "out(this.fields.status.id)")
    issue_estimate=$(echo $interested_in | jsawk -n "out(this.fields.aggregatetimeoriginalestimate)")
    echo "$issue_assignee_username|$issue_assignee|$sprint|$issue_key|$issue_summary|$issue_status|$issue_status_id|$issue_estimate" >> sprint
  done

  developers=($(sort -k 1 -t"|" sprint | cut -d"|" -f1 | uniq))
done

#printf "%-30s %-7s %-7s %-7s %-7s %-7s %-7s %-10s %s" "Developer" "Sprint" "Issues" "Done" "Working" "To-Do" "Days" "Days-Done" "Progress" > dev_report

echo "Remaining work for current sprint by developer" > dev_remaining

for developer in "${developers[@]}"
do
  echo $developer >> dev_remaining
  current_sprint=1
  for sprint in ${sprints[@]}
  do
    final=0
    if [ $current_sprint -eq 1 ]; then
      final=1
    fi
    awk -v "developer=$developer" -v "sprint=$sprint" -v "final=$final" -f process.awk sprint
    current_sprint=$((current_sprint+1))
  done
  echo "" >> dev_remaining
done

echo "Done."

echo "" >> dev_report
cat dev_remaining >> dev_report

cat dev_report

mail -s "Data Warehouse Sprint Status" -F "adam@radiumone.com" "adam@radiumone.com" "adam+1@radiumone.com" < dev_report

rm -rf sprint
rm -rf epic_response   
rm -rf epics 
rm -rf sprint_response
rm -rf dev_report
rm -rf dev_remaining
