#!/bin/bash
# Adam Cockell
# 7/9/14

# Scenario 1
# Get count of all completed issues per sprint and arrange by assignee
# Include total original time estimate per iteration
# Do this for every sprint so we have a running history of output per assignee

# Scenario 2
# Get current progress on each epic
# Print out complete and incomplete issues for each
# Email to stakeholders

username=$1
pass=$2

sprints=(125 126)

rm -rf epics
rm -rf epic_tickets
rm -rf epic_count

echo "---------------"
echo "Finding Epics: "
curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$pass "https://radiumone.jira.com/rest/api/2/search?jql=project="Datatech"%20AND%20issuetype="Epic"%20AND%20labels=DWPM&maxResults=1000" > epic_response
epic_count=$(cat epic_response | jsawk -n 'out(this.issues)' | jsawk -a 'return this.length')
echo $epic_count epics


epic_summary=()
epic_key=()
for (( cnt=0; cnt<$epic_count; cnt++ ))
do
  interested_in=$(cat epic_response | jsawk -n "out(this.issues[$cnt])")
  epic_key[cnt]=$(echo $interested_in | jsawk -n "out(this.key)")
  epic_summary[cnt]=$(echo $interested_in | jsawk -n "out(this.fields.summary)")
  echo "${epic_key[cnt]} | ${epic_summary[cnt]}" >> epics
done

for sprint in "${sprints[@]}"
do

  echo "-------------------"
  echo "Finding Non-epics in Sprint: "
  curl --silent  -H "Content-Type: application/json; charset=UTF-8" -u $username:$pass "https://radiumone.jira.com/rest/api/2/search?jql=project="Datatech"%20AND%20issuetype!="Epic"%20AND%20labels=DWPM%20AND%20sprint=$sprint+order+by+assignee&maxResults=1000" > sprint_response
  other_count=$(cat sprint_response | jsawk -n 'out(this.issues)' | jsawk -a 'return this.length')
  echo $other_count issues

  echo "-----------------------"
  echo "Finding Tickets for Sprint $sprint"

  for (( cnt=0; cnt<$other_count; cnt++ ))
  do
    interested_in=$(cat sprint_response | jsawk -n "out(this.issues[$cnt])")
    issue_assignee=$(echo $interested_in | jsawk -n "out(this.fields.assignee.displayName)")
    issue_assignee_username=$(echo $interested_in | jsawk -n "out(this.fields.assignee.name)")
    issue_summary=$(echo $interested_in | jsawk -n "out(this.fields.summary)")
    issue_key=$(echo $interested_in | jsawk -n "out(this.key)")
    issue_status=$(echo $interested_in | jsawk -n "out(this.fields.status.name)")
    issue_status_id=$(echo $interested_in | jsawk -n "out(this.fields.status.id)")
    issue_estimate=$(echo $interested_in | jsawk -n "out(this.fields.aggregatetimeoriginalestimate)")
    echo "$issue_assignee_username | $issue_assignee | $sprint | $issue_key |  $issue_summary |  $issue_status | $issue_status_id | $issue_estimate" >> sprint
  done

done

#rm -rf sprint_*
rm -rf all_response    
rm -rf epic_count
rm -rf epic_response   
rm -rf epic_tickets
rm -rf epics 
rm -rf sprint_response
